language: ruby
rvm:
 - 2.4.1
before_script:
  - bundle exec rake db:create --all
  - bundle exec rake db:migrate
  - rake create_store:create_store
  - rake add_store_id_to_items:add_store_id_to_items
script:
  - bundle exec rspec
services:
  - postgresql
notifications:
  email: false
